export const TYPES = {
  Application: Symbol.for('Application'),
  ILogger: Symbol.for('LoggerService'),
  IUserController: Symbol.for('UserController'),
  ExeptionFilter: Symbol.for('ExeptionFilter'),
  UsersRepository: Symbol.for('UsersRepository'),
  UsersService: Symbol.for('UsersService'),
  RolesService: Symbol.for('RolesService'),
  IRolesRepository: Symbol.for('RolesRepository'),
  ICollectionController: Symbol.for('CollectionController'),
  CollectionService: Symbol.for('CollectionService'),
  ICollectionRepository: Symbol.for('CollectionRepository'),
  IDeckController: Symbol.for('DeckController'),
  DeckService: Symbol.for('DeckService'),
  IDeckRepository: Symbol.for('DeckRepository'),
  CardsService: Symbol.for('CardsService'),
  ConfigService: Symbol.for('ConfigService'),
}